src/ShieldRPG/Controllers/MainController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShieldRPG.Models;
using ShieldRPG.Repositories;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ShieldRPG.Controllers
{
    [Authorize]
    public class MainController : Controller
    {
        private readonly ILogger<MainController> _logger;
        private readonly DataRepository _dataRepository;
        private readonly CenterLabRequestsRepository _centerLabRepository;

        public MainController(
            ILogger<MainController> logger,
            DataRepository dataRepository,
            CenterLabRequestsRepository centerLabRepository)
        {
            _logger = logger;
            _dataRepository = dataRepository;
            _centerLabRepository = centerLabRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "medlab")]
        public IActionResult MedLab()
        {
            return View();
        }

        [Authorize(Roles = "chemlab")]
        public IActionResult ChemLab()
        {
            return View();
        }

        [Authorize(Roles = "techlab")]
        public IActionResult TechLab()
        {
            return View();
        }

        public IActionResult CenterLab()
        {
            ClaimsPrincipal principal = HttpContext.User;
            return View(_centerLabRepository.GetRequests(principal.Identity.Name));
        }

        [Authorize(Roles = "shielddb")]
        public IActionResult ShieldDb()
        {
            return View();
        }

        public IActionResult CenterLabTest()
        {
            return View();
        }

        /*------------------------------ */

        public IActionResult ProcessRequest(string requestType)
        {
            return View(requestType);
        }

        /*------------------------------ MedLab*/

        [Authorize(Roles = "medlab")]
        [HttpPost]
        public IActionResult DnaRequest(DnaRequest dnaRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetDnaResultFor(dnaRequest?.BloodCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        [Authorize(Roles = "medlab")]
        [HttpPost]
        public IActionResult MedcartRequest(MedcartRequest dnaRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetMedcartResultFor(dnaRequest?.MedcartCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        [Authorize(Roles = "medlab")]
        [HttpPost]
        public IActionResult ToxinsRequest(ToxinsRequest toxinsRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetToxinResultFor(toxinsRequest?.ToxinsCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        [Authorize(Roles = "medlab")]
        [HttpPost]
        public IActionResult InfectRequest(InfectRequest infectRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetInfectResultFor(infectRequest?.InfectCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        [Authorize(Roles = "medlab")]
        [HttpPost]
        public IActionResult MrtRequest(MrtRequest mrtRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetMrtResultFor(mrtRequest?.MrtCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        /*------------------------------ ChemLab*/

        [Authorize(Roles = "chemlab")]
        [HttpPost]
        public IActionResult SubstanceRequest(SubstanceRequest substanceRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetSubstancResultFor(substanceRequest?.SubstanceCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        /*------------------------------ TechLab */

        [Authorize(Roles = "techlab")]
        [HttpPost]
        public IActionResult ScanRequest(ScanRequest scanRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetScanResultFor(scanRequest?.ScanCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        [Authorize(Roles = "techlab")]
        [HttpPost]
        public IActionResult SpectrogramRequest(SpectrogramRequest spectrogramRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetSpectrogramResultFor(spectrogramRequest?.SpectrogramCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        /*------------------------------ ShieldDb */

        [Authorize(Roles = "shielddb")]
        [HttpPost]
        public IActionResult PersonalDataRequest(PersonalDataRequest personalDataRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetPersonalDataResultFor(personalDataRequest?.PersonalDataCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        [Authorize(Roles = "shielddb")]
        [HttpPost]
        public IActionResult OperationsRequest(OperationsRequest operationsRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetOperationsResultFor(operationsRequest?.OperationsCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        [Authorize(Roles = "shielddb")]
        [HttpPost]
        public IActionResult ScienceRequest(ScienceRequest scienceRequest)
        {
            ClaimsPrincipal principal = HttpContext.User;
            var accessClaim = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Access);

            (bool success, string message) = _dataRepository.GetScienceResultFor(scienceRequest?.ScienceCode, int.Parse(accessClaim.Value));
            ViewData["Title"] = success ? "OK" : "Fail";

            return View("ResultView", new TestResponse { ResponseText = message });
        }

        /*------------------------------ CenterLab */

        [HttpPost]
        public IActionResult CenterLabRequest(CenterLabRequest centerLabRequest)
        {
            if (centerLabRequest == null) { return RedirectToAction("CenterLab"); }

            ClaimsPrincipal principal = HttpContext.User;
            centerLabRequest.UserName = principal.Identity.Name;
            centerLabRequest.Id = Guid.NewGuid();
            _centerLabRepository.AddRequest(centerLabRequest);
            return RedirectToAction("CenterLab");
        }

        /*------------------------------ */

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var context = HttpContext.Features.Get<IExceptionHandlerFeature>();

            return Problem(

src/ShieldRPG/Controllers/MasterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShieldRPG.Models;
using ShieldRPG.Repositories;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ShieldRPG.Controllers
{
    [Authorize(Roles = "master")]
    public class MasterController : Controller
    {
        private readonly ILogger<MainController> _logger;
        private readonly UserRepository _userRepository;
        private readonly DataRepository _dataRepository;
        private readonly CenterLabRequestsRepository _centerLabRepository;

        public MasterController(
            ILogger<MainController> logger,
            UserRepository userRepository,
            DataRepository dataRepository,
            CenterLabRequestsRepository centerLabRepository)
        {
            _logger = logger;
            _userRepository = userRepository;
            _dataRepository = dataRepository;
            _centerLabRepository = centerLabRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CenterLab()
        {
            return View(_centerLabRepository.GetRequests());
        }

        public IActionResult EditCenterLabRequest(Guid id)
        {
            return View(_centerLabRepository.GetRequestById(id));
        }

        [HttpPost]
        public IActionResult EditCenterLabRequest(CenterLabRequest centerLabRequest)
        {
            CenterLabRequest existing = _centerLabRepository.GetRequestById(centerLabRequest.Id);
            if (existing == null) { return RedirectToAction("CenterLab"); }
            existing.Response = centerLabRequest.Response;
            _centerLabRepository.AddRequest(existing);
            return RedirectToAction("CenterLab");
        }

        public IActionResult ListUsers()
        {
            return View(_userRepository.GetUsers());
        }

        public IActionResult EditUser(string login)
        {
            return View(_userRepository.GetUserDataByLogin(login));
        }

        [HttpPost]
        public IActionResult EditUser(UserRecord userRecord)
        {
            UserRecord existing = _userRepository.GetUserDataByLogin(userRecord.Login);
            if (existing == null) { return RedirectToAction("CenterLab"); }
            existing.Access = userRecord.Access != 0 ? userRecord.Access : existing.Access;
            existing.HackerRank = userRecord.HackerRank != 0 ? userRecord.HackerRank : existing.HackerRank;
            _userRepository.UpdateUserData(existing);
            return RedirectToAction("ListUsers");
        }

        public IActionResult ListDb()
        {
            return View(_dataRepository.GetRecordList());
        }

        public IActionResult EditRecord(Guid id)
        {
            return View(_dataRepository.GetRecordById(id));
        }

        [HttpPost]
        public IActionResult EditRecord(DataRecord dataRecord)
        {
            _dataRepository.UpdateRecord(dataRecord);
            return RedirectToAction("ListDb");
        }

        public IActionResult CreateRecord()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateRecord(DataRecord dataRecord)
        {
            dataRecord.Id = Guid.NewGuid();
            _dataRepository.UpdateRecord(dataRecord);
            return RedirectToAction("ListDb");
        }
    }
}

src/ShieldRPG/Views/Shared/AccessDenied.cshtml
@model ShieldRPG.Models.CenterLabRequest

@{
    ViewData["Title"] = "Ошибка";
}

<!DOCTYPE html>

<div class="row">
    <h1>Нет доступа.</h1>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/ShieldRPG/Views/Shared/_DarknetLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Darknet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/terminal.css" />
</head>
<body>
    <div class="container darknet">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/dist/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/ShieldRPG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>S.H.I.E.L.D - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Main" asp-action="Index">Main</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="MedLab">Медицинская лаборатория</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="ChemLab">Лаборатория биохимии</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="TechLab">Инженерная лаборатория</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="CenterLab">Запрос в центральную лабораторию</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="ShieldDb">База данных S.H.I.E.L.D</a>
                        </li>
                        <li class="nav-item">
                            <div class="row">
                                <div class="col-md-12">
                                    @User.Identity.Name
                                    <a asp-action="logout" asp-controller="account">
                                        Logout
                                    </a>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--modal-->
    <div class="modal" id="form-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                </div>
                <div class="modal-body"></div>
            </div>
        </div>
    </div>


    <!--modal-->

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - S.H.I.E.L.D - <a asp-area="" asp-controller="Main" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/dist/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/ShieldRPG/Views/Shared/_MasterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>S.H.I.E.L.D - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Master" asp-action="Index">Main</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Master" asp-action="CenterLab">Запросы в центральную лабораторию</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Master" asp-action="ListUsers">Редактирование пользователей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Master" asp-action="ListDb">Редактирование записей</a>
                        </li>
                        <li class="nav-item">
                            <div class="row">
                                <div class="col-md-12">
                                    @User.Identity.Name
                                    <a asp-action="logout" asp-controller="account">
                                        Logout
                                    </a>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--modal-->
    <div class="modal" id="form-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">&times;</button>
                </div>
                <div class="modal-body"></div>
            </div>
        </div>
    </div>


    <!--modal-->

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - S.H.I.E.L.D - <a asp-area="" asp-controller="Main" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/dist/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>