src/ShieldRPG/Controllers/DarknetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using ShieldRPG.Models;
using ShieldRPG.Repositories;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ShieldRPG.Controllers
{
    public class DarknetController : Controller
    {
        private readonly ILogger<MainController> _logger;
        private readonly DataRepository _dataRepository;
        private readonly WordsRepository _wordsRepository;
        private readonly UserRepository _userRepository;
        private readonly HackerRepository _hackerRepository;

        public DarknetController(
            ILogger<MainController> logger,
            DataRepository dataRepository,
            WordsRepository wordsRepository,
            UserRepository userRepository,
            HackerRepository hackerRepository)
        {
            _logger = logger;
            _dataRepository = dataRepository;
            _wordsRepository = wordsRepository;
            _userRepository = userRepository;
            _hackerRepository = hackerRepository;
        }

        [Authorize(Roles = "darknet")]
        public IActionResult Index()
        {
            var list = _dataRepository.GetRecordList("prd", "ops", "sci", "medcart")
                .Select(record => new DataRecordView(record));
            return View(list);
        }

        [Authorize(Roles = "darknet")]
        public IActionResult Terminal(Guid id)
        {
            return View(_dataRepository.GetRecordById(id));
        }

        [HttpGet]
        public IActionResult AttemptFinished(bool success)
        {
            ClaimsPrincipal principal = HttpContext.User;
            string login = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Login)?.Value;
            _hackerRepository.UpdateAttempt(login, success);

            return Ok();
        }

        public IActionResult GetAssesmentData(int count, int length)
        {
            ClaimsPrincipal principal = HttpContext.User;

            string login = principal.Claims.FirstOrDefault(claim =>
                claim.Type == ShieldRpgClaimTypes.Login)?.Value;

            if (!_hackerRepository.CanHack(login))
            {
                return Json(string.Empty);
            }
            
            var userData = _userRepository.GetUserDataByLogin(login);
            var assesment = new AssesmentResult
            {
                Attempts = _hackerRepository.GetAttempts(userData.HackerRank),
                Words = _wordsRepository.GetWords(count, length)
            };

            return Json(JsonConvert.SerializeObject(assesment));
        }

        public IActionResult GetDataRecord(Guid id)
        {
            var record = _dataRepository.GetRecordById(id);

            return Json(JsonConvert.SerializeObject(record));
        }
    }
}

src/ShieldRPG/Views/Darknet/Index.cshtml
@model IEnumerable<ShieldRPG.Repositories.DataRecordView>

@{
    Layout = "~/Views/Shared/_DarknetLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DBList</title>
</head>
<body>
    <table class="table" id="darknet">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RequestType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Access)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    <p>
                        <a class="darknet" href="@Url.Action("Terminal", "Darknet", new { id = item.Id }, Context.Request.Scheme)">
                            @Html.DisplayFor(modelItem => item.Code)
                        </a>
                    </p>

                </td>
                <td>
                    <p>
                        @Html.DisplayFor(modelItem => item.RequestType)
                    </p>
                </td>
                <td>
                    <p>
                        @Html.DisplayFor(modelItem => item.Access)
                    </p>
                </td>
            </tr>
            }
        </tbody>
    </table>
</body>
</html>

src/ShieldRPG/Views/Darknet/Terminal.cshtml
@model ShieldRPG.Repositories.DataRecord
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Darknet</title>
</head>
<body onclick="TogglePower()">
    <link rel="stylesheet" href="~/css/terminal.css" />
    <div id="terminal">
        <h1>CLICK</h1>
    </div>
    <div id="otheraudiostuff">
        <audio id="poweron" src="~/sound/poweron.ogg"></audio>
        <audio id="poweroff" src="~/sound/poweroff.ogg"></audio>
        <audio id="passbad" src="~/sound/passbad.ogg"></audio>
        <audio id="passgood" src="~/sound/passgood.ogg"></audio>
    </div>
    <div id="audiostuff">
        <audio id="enter" src="~/sound/kenter.ogg"></audio>
        <audio id="k1" src="~/sound/k1.ogg"></audio>
        <audio id="k2" src="~/sound/k2.ogg"></audio>
        <audio id="k3" src="~/sound/k3.ogg"></audio>
        <audio id="k4" src="~/sound/k4.ogg"></audio>
        <audio id="k5" src="~/sound/k5.ogg"></audio>
        <audio id="k6" src="~/sound/k6.ogg"></audio>
        <audio id="k7" src="~/sound/k7.ogg"></audio>
        <audio id="k8" src="~/sound/k8.ogg"></audio>
        <audio id="k9" src="~/sound/k9.ogg"></audio>
        <audio id="k10" src="~/sound/k10.ogg"></audio>
    </div>

    <input asp-for="Id" type="hidden" />
    <script src="~/lib/three/dist/three.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/terminal.js" asp-append-version="true"></script>
</body>
</html>